### ISSUE TITLE
Not optimized result

### ISSUE THREAD

**Issue by erikhagemeijer** [ModischFabrications/CutSolver#53]
Hello, I am testing CutSolver and when trying a job I don't get an optimal solution:
Is there a way to select the solver type?
Thanks for your efforts!
{
  "job": {
    "max_length": 6500,
    "cut_width": 20,
    "target_sizes": {
      "1258": 2,
      "3958": 2
    }
  },
  "solver_type": "bruteforce",
  "time_us": 85,
  "lengths": [
    [
      3958
    ],
    [
      3958,
      1258
    ],
    [
      1258
    ]
  ]
}

**Comment by ModischFabrications** [comment]
Thanks for testing, that is definitely weird, thanks for the repro. Solver selection is planned, see #5 , but brute force should give guaranteed best solutions up to 12 entries. I haven't looked into the code for a while, do you have the means to debug yourself?

**Comment by ModischFabrications** [comment]
Just tested it out on a local installation, seems like it works on my end: 

```
{
  "job": {
    "max_length": 6500,
    "cut_width": 20,
    "target_sizes": {
      "1258": 2,
      "3958": 2
    }
  },
  "solver_type": "bruteforce",
  "time_us": 137,
  "lengths": [
    [
      3958,
      1258
    ],
    [
      3958,
      1258
    ]
  ]
}
```

Can you pull the newest image, restart the application and try again with these values?

**Comment by erikhagemeijer** [comment]
Hello Robin,

I tested cutsolver until now through a php development environment and run the app from within.

I installed Docker on my Synology and am using this now. Luckily I see the same result now as you did!

I’m a Filemaker developer and am going to use your software in a Filemaker project. Sorry I can’t help you with this project.

Greatings,

Erik Hagemeijer.

**Comment by ModischFabrications** [comment]
Huh, weird that the other environment gives wrong results, but good that it works now. 
Sounds interesting, feel free to send a reference if you intend to make it public.
