### ISSUE TITLE
[Bug] Zero cutting width not working with FFD

### ISSUE THREAD

**Issue by ecdlguy** [ModischFabrications/CutSolver#59]
Hi, 

I've done a simple test, see screenshot:
![Bildschirmfoto von 2023-07-19 13-06-07](https://github.com/ModischFabrications/CutSolverFrontend/assets/8693760/20a12762-960d-45d2-9057-f57287f8da2a)

Using "cutting width = 0", shouldn't this yield 10 parts per rod?

cheers,
Thorsten

**Comment by ecdlguy** [comment]
Is [https://cutsolver.modisch.me/](https://cutsolver.modisch.me/) already using the fix?

![Bildschirmfoto vom 2024-04-03 11-04-29](https://github.com/ModischFabrications/CutSolver/assets/8693760/c64847d6-b24f-4d9a-bcd9-3002b7d263ae)

**Comment by ModischFabrications** [comment]
Not yet, will try to release an update this week. Online version is v1.0.0, new one is v1.0.1

**Comment by ModischFabrications** [comment]
Just updated, check it out 😉 
Out of curiosity: What are you using it for? I haven't found a use for zero width cuts yet
