### ISSUE TITLE
[Bug] Bruteforce applies cuts a second time

### ISSUE THREAD

**Issue by Bouni** [ModischFabrications/CutSolver#63]
The different solvers return different results

Bruteforce:

![grafik](https://github.com/ModischFabrications/CutSolver/assets/948965/62b5282e-9f56-443e-919d-12809de97dcb)

FFD:

![grafik](https://github.com/ModischFabrications/CutSolver/assets/948965/71b558aa-2891-4cf8-a0f9-0a97c196ca8b)

The FFD result is orrect in my opinion. `2x 495 = 990 + 6 = 996` => Two pieces should fit into one stock of 1000

I would propose to ditch the Bruteforce algorithm altogether as it doesn't matter if the FFD is sub milliseconds slower when used for < 10 items. Above that threshold the FFD comes into action anyway and that way we do not have to maintain two different algorithms.

The same goes for the gapfill algorithm.

**Comment by ModischFabrications** [comment]
Brute force might apply the cut weight a second time, but haven't checked. Might also be related to #59 

Gapfill was my first (rather stupid) try if I remember correctly, it should have a comment somewhere. That one can definitely go. 

Bruteforce is important. It's definitely way slower, but it's the only way to get the perfect result. I only disable it above 11 entries because it will run too long otherwise. FFD is infinitely faster, but can be tricked, I think it can be up to 50% worse.

**Comment by Bouni** [comment]
🤔 Ok, havn't checkt to many variants of bruteforce against FFD to be honest.
We should defenitely implement material utilisation into the result, with that we can compare both algorithms and can probably implment some random input comparison benchmarks.

**Comment by ModischFabrications** [comment]
Bruteforce isn't very complex, it's really just testing every single combination, giving out the best one. That's the simple reason it can guarantee the best outcome. 

I think I have some basic benchmarks in the units tests, I think I actually use the remaining length to evaluate the results of bruteforce.

**Comment by ModischFabrications** [comment]
Hey, any progress here? I might look into it the next few weeks, together with https://github.com/ModischFabrications/CutSolver/issues/52

**Comment by ModischFabrications** [comment]
I found the old benchmarks, not much to see there: 18d760b0debafc609ab45fdf8f39ebc4bae18c8a

I created new tests in test_large , we can add random inputs there if you want. 

The difference is pretty irrelevant though: <8 entries are done instantly and might as well be perfect with bruteforce, >11 entries take too long for bruteforce and can only be solved with FFD.
