### ISSUE TITLE
Allow items with a length equal to stock length

### ISSUE THREAD

**Issue by Bouni** [ModischFabrications/CutSolver#64]
At the moment when I have a stock length of lets say 1500, an item of 1500 leads to an error because of the cut width.

I think it should be easy to check if an item is equal to the stock length (or rather stock length - cut_width) and allow that special case.

**Comment by ModischFabrications** [comment]
This will probably work without additional effort when the solver algorithms are fixed.

**Comment by ModischFabrications** [comment]
FFD handles it correctly, bruteforce doesn't (probably because of #63 ). Would still be useful to catch it earlier and save computation.
