### ISSUE TITLE
Freeze (100% cpu usage) on solve

### ISSUE THREAD

**Issue by telaak** [ModischFabrications/CutSolver#74]
Certain input e.g. 
``` js
{
    cut_width: 0,
    max_length: 600,
    target_sizes: [{ length: "106", quantity: "12" }],
}
```

causes uvicorn (at least according to top) to go up to 100% cpu usage, freeze and be unable to respond to any request until restarted.

The hosted version at [https://cutsolver.modisch.me/](https://cutsolver.modisch.me/) is also currently stuck due to this.

**Comment by ModischFabrications** [comment]
Oh wow, didn't notice that,  must have been at least a week. Thanks for saying something! 

I have restarted the instance and am looking into fixing it, potentially by updating the frontend to the new v1.1.0 format.

**Comment by ModischFabrications** [comment]
The pure solver with proper env setup should have been working since v1.1.0, the frontend was also updated in https://github.com/ModischFabrications/CutSolverFrontend/pull/75

Do remember to update your API usage if you host it yourself.
